package com.zys.dao;

import com.zys.entitys.UserInfo;

public interface UserInfoMapper {
    /**
     * 根据ID删除
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * 添加
     * @mbggenerated
     */
    int insert(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_infor
     *
     * @mbggenerated
     */
    int insertSelective(UserInfo record);

    /**
     * 查询是否存在
     * @mbggenerated
     */
    UserInfo selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_infor
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserInfo record);

    /**
     * 更新，根据主键更新
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserInfo record);
}